apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r35fpksdn-go
  janus-idp.io/tekton: r35fpksdn-go
  backstage.io/kubernetes-id: r35fpksdn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r35fpksdn-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
